name: Setup SteamCMD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run server
      run: >
        docker run -it
        -p 27015:27015/tcp
        -p 27015:27015/udp
        -e "AUTHKEY=${{ secrets.STEAM_WEB_API_KEY }}"
        -e "GLST=${{ secrets.GAME_SERVER_LOGIN_TOKEN }}"
        -e "GAMEMODE=sandbox"
        -e "MAP=gm_construct"
        -e "WORKSHOPCOLLECTIONID=${{ secrets.WORKSHOP_COLLECTION_ID }}"
        hackebein/garrysmod
