name: Setup SteamCMD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run server
      run: docker run \
        -p 27015:27015/tcp \
        -p 27015:27015/udp \
        -e "AUTHKEY=5EA0376B4D9F011724E955F7116876D2" \
        -e "GAMEMODE=terrortown" \
        -e "MAP=ttt_minecraft_b5" \
        -e "WORKSHOPCOLLECTIONID=843519054" \
        -v ./server.cfg:/opt/steam/garrysmod/cfg/server.cfg \
        hackebein/garrysmod
